const output = {
  status: "ok",
  total_hits: 10000,
  page: 6,
  total_pages: 200,
  page_size: 50,
  articles: [
    {
      title: "Goshen Theater registration",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.abc57.com/news/goshen-theater-registration",
      clean_url: "abc57.com",
      excerpt:
        "Studio registrations for Goshen Theater's Winter/Spring 2023 will close on January 6, 2023.",
      summary:
        "By: Spencer Beehler Posted: Jan 3, 2023 7:54 PM EST ELKHART COUNTY, Ind. --Studio registrations for Goshen Theater's Winter/Spring 2023 will close on January 6, 2023.\u00a0Classes will begin on January 9 and continue through March 31.\u00a0You can join for weekly acting, dance, and vocal studio classes for students between ages 8-18 years old.\u00a0Financial aid, family discounts, and flexible payment plans are offered as well.\u00a0For more information, visit www.GoshenTheater.com/education/classes or email [email\u00a0protected].",
      rights: "abc57.com",
      rank: 28673,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://newscdn2.weigelbroadcasting.com/IQzXR-1672793922-245043-blog-Goshen%20Theater.jpg.png",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "57d3c8058e04ac95bccc3c3497c01057",
    },
    {
      title: "Two dead after head-on collision with semi-truck on Highway 42",
      author: "Robert Desaulniers",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kezi.com/news/two-dead-after-head-on-collision-with-semi-truck-on-highway-42/article_5a8dbd46-8bc6-11ed-8d1b-ff502e199c89.html",
      clean_url: "kezi.com",
      excerpt:
        "Police said an SUV towing another SUV crashed into a semi-truck after crossing into the oncoming lane.",
      summary:
        "WINSTON, Ore. -- Two people are dead after crashing head-on into a semi-truck on Highway 42 Monday night, Oregon State Police said.According to OSP, troopers responded to Highway 42 milepost 70.5, just southwest of Winston, at about 9:30 p.m. on January 2. There, they said they found a GMC Yukon was towing another GMC Yukon when it crossed into the oncoming lane for an unknown reason and crashed into a semi-truck head-on. Troopers said the operator of the Yukon, Jimmy Brown, 35, of Ten Mile, and the passenger in the Yukon, Jason Elam, 35, also of Ten Mile, suffered fatal injuries in the crash and were pronounced deceased at the scene.",
      rights: "kezi.com",
      rank: 34762,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Robert Desaulniers",
      media:
        "https://bloximages.newyork1.vip.townnews.com/kezi.com/content/tncms/assets/v3/editorial/c/66/c66e0290-9271-11ec-86d6-43e60bbd5f53/6212790fdbb98.image.jpg?crop=640%2C336%2C0%2C11&resize=640%2C336&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@KEZI9",
      _score: null,
      _id: "7fdb380e8c43df35a04c5fa4a819bd83",
    },
    {
      title:
        "The first Reboot'D single from Bobby Blakdout new series features Paul Wall and former Death Row Records artist SKG!",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://news.kisspr.com/2023/01/03/the-first-rebootd-single-from-bobby-blakdout-new-series-features-paul-wall-and-former-death-row-records-artist-skg_483852.html",
      clean_url: "kisspr.com",
      excerpt:
        "The first Reboot'D single from Bobby Blakdout new series features Paul Wall and former Death Row Records artist SKG!",
      summary:
        "Reboot'D is a fresh new series, featuring cutting-edge tracks that showcase Bobby Blakdout's unique style and ability to adapt his sound. With a mix of electronic, hip hop, and pop influences, the Reboot'D series is sure to get you moving and keep you coming back for more.The first Reboot'D single of the series titled 'Big Chains, Big Grill - Reboot'D' is available now on all major streaming platforms and has charted #5 on the iTunes Top 200 as well as Genius, Shazam, and other platforms! For more updates on new singles visit the Blak'd Out Records website and official Blak'd Out Instagram or check out Reboot'D on Instagram!Don't miss out on these exciting new releases from Bobby Blakdout and Blak'd Out Records.",
      rights: "theusnews.com",
      rank: 248881,
      topic: "news",
      country: "unknown",
      language: "en",
      authors: "",
      media: "https://im.submitmypressrelease.com/info/483852",
      is_opinion: false,
      twitter_account: "@the_usnews",
      _score: null,
      _id: "fd7ca7c60b25a069781b054d43211cf7",
    },
    {
      title: "Activists Slam Trump for Blaming Pro Life for Midterms",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kvor.com/news/activists-slam-trump-for-blaming-pro-life-for-midterms",
      clean_url: "kvor.com",
      excerpt: "Activists Slam Trump for Pinning GOP Losses on Pro-Lifers",
      summary:
        "Activists are slamming former President Donald Trump for pinning the GOP midterm losses on the pro-life movement.\n\nThe former president took to his social media platform Truth Social on Sunday to argue the disappointing performance of Republicans in the midterms was not his 'fault.'\n\n'It was the \u2018abortion issue,' poorly handled by many Republicans, especially those that firmly insisted on no exceptions, even in the case of rape, incest, or life of the mother, that lost large numbers of voters,' Trump wrote.",
      rights: "kvor.com",
      rank: 507076,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://express-images.franklymedia.com/asset/express-cms-admin-logo.png",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "3ce3191954faa7a87c58378823efaf01",
    },
    {
      title:
        "ROSEN, A HIGHLY RECOGNIZED LAW FIRM, Encourages BioLineRx Ltd. Investors to Inquire About Securities Class Action Investigatio",
      author: "ACCESSWIRE 4th",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.bignewsnetwork.com/news/273310553/rosen-a-highly-recognized-law-firm-encourages-biolinerx-ltd-investors-to-inquire-about-securities-class-action-investigatio---blrx",
      clean_url: "bignewsnetwork.com",
      excerpt:
        "ACCESSWIRE 4th January 2023, 11:55 GMT+11NEW YORK, NY / ACCESSWIRE / January 3, 2023 / WHY: Rosen Law Firm, a global investor rights law firm, continues its investigation of potential civil securities\u2026",
      summary:
        "ACCESSWIRE 4th January 2023, 11:55 GMT+11NEW YORK, NY / ACCESSWIRE / January 3, 2023 / WHY: Rosen Law Firm, a global investor rights law firm, continues its investigation of potential civil securities claims on behalf of shareholders of BioLineRx Ltd. (NASDAQ:BLRX) resulting from allegations that BioLineRx may have issued materially misleading business information to the investing public.SO WHAT: If you purchased BioLineRx securities you may be entitled to compensation without payment of any out of pocket fees or costs through a contingency fee arrangement.",
      rights: "bignewsnetwork.com",
      rank: 5608,
      topic: "news",
      country: "US",
      language: "en",
      authors: "ACCESSWIRE 4th",
      media:
        "https://www.accesswire.com/users/newswire/images/733795/image.png",
      is_opinion: false,
      twitter_account: "@BigNewsNetwork",
      _score: null,
      _id: "bb5f3eec052d04f187923d70b21a761a",
    },
    {
      title:
        "City asks artists to submit work for display at Durango rec center",
      author: "Christian Burney",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.durangoherald.com/articles/city-asks-artists-to-submit-work-for-display-at-durango-rec-center/",
      clean_url: "durangoherald.com",
      excerpt:
        "Local artists looking for exposure have an opportunity to share their work with the public at the Durango Community Recreation Center. The city of Durango has issued a call to local artists,\u2026",
      summary:
        "Pieces to be hosted for one month at a time; applications taken on first-come-first-serve basis Local artists looking for exposure have an opportunity to share their work with the public at the Durango Community Recreation Center. The city of Durango has issued a call to local artists, inviting them to apply to have their work showcased in the community wing for a month at a time. John Robinette, recreation center manager, said applications are reviewed on a first-come-first-serve basis. The city is seeking 2D artwork across all mediums to hang in the community wing.",
      rights: "durangoherald.com",
      rank: 13843,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Christian Burney",
      media:
        "https://imengine.public.prod.dur.navigacloud.com/?uuid=df0cda7f-3b2e-5884-886f-66f4b591cf98&function=fit&type=preview",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "e8b82ce5dfa1dab3e91fbaad4c3fd0f7",
    },
    {
      title:
        "Waterford News & Star \u2014 Aleksandar Mitrovic effort enough as Fulham boost European charge at Leicester",
      author: "ter",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://waterford-news.ie/2023/01/03/aleksandar-mitrovic-effort-enough-as-fulham-boost-european-charge-at-leicester/",
      clean_url: "waterford-news.ie",
      excerpt:
        "Tuesday, January 03, 2023 By Nick Mashiter, PA Aleksandar Mitrovic boosted Fulham's European charge as the Cottagers downed Leicester with a narrow win on Tuesday night. The striker fired Marco\u2026",
      summary:
        "Tuesday, January 03, 2023 \n\nBy Nick Mashiter, PA\nAleksandar Mitrovic boosted Fulham's European charge as the Cottagers downed Leicester with a narrow win on Tuesday night.\nThe striker fired Marco Silva's side to a third-straight win after a 1-0 Premier League victory at the King Power Stadium.\nIt left Fulham seventh in the Premier League on 28 points \u2013 the same amount they were relegated with in 2021 \u2013 and level with Liverpool.\nThe Cottagers are in dreamland, in contrast to the Foxes with boss Brendan Rodgers' consistent reality checks still ringing true after a third-straight defeat.",
      rights: "waterford-news.ie",
      rank: 281156,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "ter",
      media:
        "https://img.resized.co/breaking-news/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5icmVha2luZ25ld3MuaWVcXFwvcHJvZFxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDFcXFwvMDMyMjAyNDJcXFwvMi43MDQzNzgxOC1lMTY3Mjc4MzQyMDE0Mi5qcGdcIixcIndpZHRoXCI6NjAwLFwiaGVpZ2h0XCI6bnVsbCxcImRlZmF1bHRcIjpcImh0dHBzOlxcXC9cXFwvd3d3LmJyZWFraW5nbmV3cy5pZVxcXC9pbWFnZXNcXFwvbm8taW1hZ2UucG5nXCIsXCJvcHRpb25zXCI6W119IiwiaGFzaCI6IjZiZTc2MmU3NmM2OWE2NWJhNTE3ZDMxZTViZmRmZTA5ODg1NDVjYmMifQ==/2-70437818-e1672783420142.jpg",
      is_opinion: false,
      twitter_account: "@waterfordNS",
      _score: null,
      _id: "e25dbf9874e175a374f3e06dc3197d70",
    },
    {
      title: "New Bolt offers more bang for the buck",
      author: "Mike Hagerty",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.losaltosonline.com/auto/new-bolt-offers-more-bang-for-the-buck/article_15974e16-8bba-11ed-a625-07c17993e355.html",
      clean_url: "losaltosonline.com",
      excerpt:
        "In a year where the inescapable word has been 'inflation,' Chevrolet has done something remarkable \u2013 it has slashed the price of its Bolt EV and Bolt EUV electric cars.",
      summary:
        "The electric engine in the new Chevrolet Bolt makes 200 horsepower, taking the car from 0 to 60 mph in 6.8 seconds. Mike Hagerty/Special to the Town Crier",
      rights: "losaltosonline.com",
      rank: 80740,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Mike Hagerty",
      media:
        "https://bloximages.newyork1.vip.townnews.com/losaltosonline.com/content/tncms/assets/v3/editorial/8/c6/8c6c1eea-8bba-11ed-9b41-1b0668c264a0/63b4b403489bd.image.jpg?crop=1662%2C873%2C0%2C187&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@latc",
      _score: null,
      _id: "baa05648cd3ae0bebd69d43329ed34dd",
    },
    {
      title: "Fitness schemes prevalent in the new year",
      author: "Niccole Caan",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kens5.com/article/news/local/fitness-schemes-san-antonio-new-year-goals-healthy/273-cc840372-b531-4bb4-ace5-922d9ed30dba",
      clean_url: "kens5.com",
      excerpt:
        "A new year often means a new health plan. Schemers know there is interest in fitness and they are taking advantage, but do not let them take your money.",
      summary:
        "SAN ANTONIO \u2014 Ads, emails or texts about 'miracle' weight loss products will be tempting. 'Everybody wants to lose 20 pounds in two weeks. It sounds great, but really got to get deep down into what is realistic,' said Jason Meza, regional director for the Better Business Bureau. 'What is a realistic goal for you? Will it put more stress on your body than is healthy? Have you reached out to a doctor?' Claims of amazing outcomes often come with a monthly charge that is hard to cancel or a high price with few results.",
      rights: "kens5.com",
      rank: 10321,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Niccole Caan",
      media:
        "https://media.kens5.com/assets/KENS/images/6667ff9a-dcdd-4e97-9609-fb18bdb99966/6667ff9a-dcdd-4e97-9609-fb18bdb99966_1140x641.jpg",
      is_opinion: false,
      twitter_account: "KENS5",
      _score: null,
      _id: "181a0bdb27aef097513f784445bb1684",
    },
    {
      title: "Photos: Scenes from the 1st day of the 118th Congress",
      author: "J. Scott plewhite",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://qconline.com/news/national/photos-scenes-from-the-1st-day-of-the-118th-congress/collection_0bdd09c8-fcb1-507d-bc3c-6f3f5b0c7047.html",
      clean_url: "qconline.com",
      excerpt: "Click here to view this item from https://qconline.com.",
      summary:
        "House Republican Leader Kevin McCarthy, R-Calif., emerges from a closed-door meeting with the GOP Conference as he pursues the speaker of the House role as the 118th Congress convenes, at the Capitol in Washington, Tuesday, Jan. 3, 2023. (AP Photo/J. Scott Applewhite) J. Scott Applewhite Rep. Marjorie Taylor Greene, R-Ga., stops to speak with reporters as she walks from a closed-door meeting with the GOP Conference during the opening day of the 118th Congress at the U.S. Capitol in Washington, Tuesday, Jan 3, 2023.",
      rights: "qconline.com",
      rank: 16776,
      topic: "news",
      country: "US",
      language: "en",
      authors:
        "Alex Brandon,Andrew Harnik,Associated Press,Carolyn Kaster,J. Scott Applewhite",
      media:
        "https://bloximages.newyork1.vip.townnews.com/qconline.com/content/tncms/assets/v3/editorial/0/bd/0bdd09c8-fcb1-507d-bc3c-6f3f5b0c7047/63b4a90fdcd86.preview.jpg?crop=1024%2C538%2C0%2C72&resize=1024%2C538&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@dispatch_argus",
      _score: null,
      _id: "4361b473d780f348c4ba37411bce7edf",
    },
    {
      title:
        "Waterford News & Star \u2014 Everton thrashed by Brighton as pressure intensifies on Frank Lampard",
      author: "ter",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://waterford-news.ie/2023/01/03/everton-thrashed-by-brighton-as-pressure-intensifies-on-frank-lampard/",
      clean_url: "waterford-news.ie",
      excerpt:
        "Tuesday, January 03, 2023 By Carl Markham, PA A new year brought no change in fortune for beleaguered Everton manager Frank Lampard as Goodison Park turned toxic after Brighton recorded their biggest\u2026",
      summary:
        "Tuesday, January 03, 2023 \n\nBy Carl Markham, PA\nA new year brought no change in fortune for beleaguered Everton manager Frank Lampard as Goodison Park turned toxic after Brighton recorded their biggest away win \u2013 4-1 \u2013 in the Premier League.\nAny sliver of confidence gained from the weekend's creditable draw at Manchester City was shattered by a performance lacking guts and guile and justifiably greeted with loud boos.\nIt was typified by a catastrophic seven-minute spell at the start of the second half in which they conceded three soft goals to 18-year-old Evan Ferguson, Solly March and Pascal Gross to add to Kaoru Mitoma's early first-half strike.",
      rights: "waterford-news.ie",
      rank: 281156,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "ter",
      media:
        "https://img.resized.co/breaking-news/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5icmVha2luZ25ld3MuaWVcXFwvcHJvZFxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDFcXFwvMDMyMTUyMDJcXFwvMi43MDQzODc3NC5qcGdcIixcIndpZHRoXCI6NjAwLFwiaGVpZ2h0XCI6bnVsbCxcImRlZmF1bHRcIjpcImh0dHBzOlxcXC9cXFwvd3d3LmJyZWFraW5nbmV3cy5pZVxcXC9pbWFnZXNcXFwvbm8taW1hZ2UucG5nXCIsXCJvcHRpb25zXCI6W119IiwiaGFzaCI6ImIzNTIzNmEzMDE5MTg1NjgxYjZjOWU0ZWFjYjMyN2IzMDVmNWFiYTIifQ==/2-70438774.jpg",
      is_opinion: false,
      twitter_account: "@waterfordNS",
      _score: null,
      _id: "eab85fb056ef0f77b288293b1a5b272b",
    },
    {
      title: "Fire damages garage on EC's west side",
      author: "Leader-Telegram Staff",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.leadertelegram.com/news/daily-updates/fire-damages-garage-on-ecs-west-side/article_1dc8e740-c35e-59b4-ba3f-bb482cbea13c.html",
      clean_url: "leadertelegram.com",
      excerpt:
        "EAU CLAIRE \u2014 A fire Tuesday afternoon caused $25,000 damage to a garage at a duplex on Eau Claire's west side.",
      summary:
        "Country\n\nUnited States of America US Virgin Islands United States Minor Outlying Islands Canada Mexico, United Mexican States Bahamas, Commonwealth of the Cuba, Republic of Dominican Republic Haiti, Republic of Jamaica Afghanistan Albania, People's Socialist Republic of Algeria, People's Democratic Republic of American Samoa Andorra, Principality of Angola, Republic of Anguilla Antarctica (the territory South of 60 deg S) Antigua and Barbuda Argentina, Argentine Republic Armenia Aruba Australia,",
      rights: "leadertelegram.com",
      rank: 26084,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Leader-Telegram Staff",
      media:
        "https://bloximages.chicago2.vip.townnews.com/leadertelegram.com/content/tncms/assets/v3/editorial/1/dc/1dc8e740-c35e-59b4-ba3f-bb482cbea13c/63b4add1ef6e9.preview.jpg?crop=1280%2C672%2C0%2C144&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@leadertelegram",
      _score: null,
      _id: "f58f6f1783e0724044238811f6816995",
    },
    {
      title: "guillotine",
      author: "Lord Brawl",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://everything2.com/title/guillotine",
      clean_url: "everything2.com",
      excerpt:
        "Log in or register to write something here or to contact authors.",
      summary:
        "Log in or register to write something here or to contact authors.",
      rights: "everything2.com",
      rank: 7517,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Lord Brawl",
      media: "https://everything2.com:443/favicon.ico",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "ae8fc903aa9d3378e884f78f28bb9da4",
    },
    {
      title: "Pelicans star Zion Williamson (hamstring) out at least 3 weeks",
      author: "Field Level Media 4th",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.bignewsnetwork.com/news/273310548/pelicans-star-zion-williamson-hamstring-out-at-least-3-weeks",
      clean_url: "bignewsnetwork.com",
      excerpt:
        "The New Orleans Pelicans announced Tuesday that star forward Zion Williamson will be re-evaluated in three weeks after suffering a right hamstring strain Monday",
      summary:
        "Field Level Media 4th January 2023, 11:40 GMT+11The New Orleans Pelicans announced Tuesday that star forward Zion Williamson will be re-evaluated in three weeks after suffering a right hamstring strain Monday.In a 120-111 loss to the Philadelphia 76ers, Williamson led the Pelicans with 26 points, seven assists and six rebounds but left the game early in the second half with the hamstring strain and was deemed out midway through the fourth.He underwent an MRI on Tuesday and was ruled out for Wednesday's home game against the Houston Rockets before the team's announcement.",
      rights: "bignewsnetwork.com",
      rank: 5608,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Field Level Media,Field Level Media 4th",
      media: "https://cdn.bignewsnetwork.com/flm1672792801.jpg",
      is_opinion: false,
      twitter_account: "@BigNewsNetwork",
      _score: null,
      _id: "0300db54b5b177b9b811ce271c672df9",
    },
    {
      title: "Limestone County teen's capital murder trial delayed until April",
      author: "Nicole Zedeck",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.waaytv.com/news/limestone-county-teens-capital-murder-trial-delayed-until-april/article_33d8b0c4-8bbd-11ed-9cf8-a3b6a2bb5154.html",
      clean_url: "waaytv.com",
      excerpt:
        "The Limestone County teen accused of killing five family members has a few more months in jail before his new trial.",
      summary:
        "WAAY 31 got Mason Sisk's reaction to the ruling. The Limestone County teen accused of killing five family members has a few more months in jail before his new trial.On Tuesday, Judge Chadwick Wise delayed Mason Sisk's capital murder trial until April 10 due to a scheduling conflict.The evidence that led to a mistrial was also discussed, as the judge clarified both parties now had equal access to Mary Sisk's phone, which had been unlocked during the trial last September.The state also presented its DNA findings from the sample taken from Sisk in December.",
      rights: "waaytv.com",
      rank: 18998,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Nicole Zedeck",
      media:
        "https://bloximages.newyork1.vip.townnews.com/waaytv.com/content/tncms/assets/v3/editorial/8/f4/8f4e7e34-8bbd-11ed-8cd4-4f781c92cac5/63b4b90808594.image.png?crop=1162%2C610%2C0%2C38&resize=1162%2C610&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@WAAYTV",
      _score: null,
      _id: "9e837029d05c097b454e7a9cf87b9ea1",
    },
    {
      title: "\u2018Pel\u00e9's magic doesn't fit in a trophy room'",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.durangoherald.com/articles/peles-magic-doesnt-fit-in-a-trophy-room/",
      clean_url: "durangoherald.com",
      excerpt:
        "The simplest way to capture the achievements of Edson Arantes do Nascimento, Brazil's unparalleled Pel\u00e9, is to tally the numbers. In two decades, he scored 1,283 goals (although the exact number\u2026",
      summary:
        "The simplest way to capture the achievements of Edson Arantes do Nascimento, Brazil's unparalleled Pel\u00e9, is to tally the numbers. In two decades, he scored 1,283 goals (although the exact number sometimes is disputed) \u2013 1,000 of them before he was 30 and 95, wearing the national team colors. He helped bring home three of Brazil's five World Cups, a feat unequaled by any other player to this day. But soccer is not a ledger, and Pel\u00e9's magic doesn't fit in a trophy room. When colon cancer killed him Thursday at age 82, the country lost a bit of its soul.",
      rights: "durangoherald.com",
      rank: 13843,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://imengine.public.prod.dur.navigacloud.com/?uuid=5decbf95-2349-5cd4-8444-ccc8c051aa39&function=fit&type=preview",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "73dd79420b18541301e6529599bcf808",
    },
    {
      title:
        "Residents ponder beam of light captured on Bayfield man's front porch camera",
      author: "Megan K. Olsen",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.durangoherald.com/articles/residents-ponder-beam-of-light-captured-on-bayfield-mans-front-porch-camera/",
      clean_url: "durangoherald.com",
      excerpt:
        "Bayfield resident Erik Carlson noticed something peculiar when reviewing the footage of his front porch camera from the night of Dec. 30. There was a strange light beaming into the sky, and every few\u2026",
      summary:
        "Fire chief suspects a gas flare, but others share more imaginative ideas Bayfield resident Erik Carlson noticed something peculiar when reviewing the footage of his front porch camera from the night of Dec. 30. There was a strange light beaming into the sky, and every few seconds, it would brighten the entire Bayfield neighborhood behind the Speedway on U.S. Highway 160. Carlson posted the video to nextdoor.com with the caption: 'Last night my front porch camera caught this beam of light shooting into the sky for hours and hours over again.",
      rights: "durangoherald.com",
      rank: 13843,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Megan K. Olsen",
      media:
        "https://imengine.public.prod.dur.navigacloud.com/?uuid=da827896-53b3-5c67-ae7e-81e1a0b13d56&function=fit&type=preview",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "e97ee4e09ff732dc5eae53acb8e5f325",
    },
    {
      title: "Moran promises results, not rhetoric",
      author: "Michael Cavazos",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.news-journal.com/news/moran-promises-results-not-rhetoric/article_9ea31f50-8b6f-11ed-86b2-a71b4dc9ed39.html",
      clean_url: "news-journal.com",
      excerpt:
        "LUFKIN \u2014 For 18 years, East Texans have been represented in Congress by a prominent Republican known more for propagating conspiracy theories than for passing laws. But the region's new",
      summary:
        "LUFKIN \u2014 For 18 years, East Texans have been represented in Congress by a prominent Republican known more for propagating conspiracy theories than for passing laws. But the region's new representative, Congressman-elect Nathaniel Moran, plans to strike a different tone in Washington, D.C.The retired Smith County judge, also a Republican, is among seven newly elected members of Congress from Texas to be sworn in Tuesday, joining 31 other Texans in the U.S. House of Representatives.Moran will represent a 10,000 mile swath that encompasses all or part of 17 counties and serves more than 700,000 people who have historically favored Republicans.",
      rights: "tylerpaper.com",
      rank: 16595,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Alex Dominguez,Michael Cavazos",
      media:
        "https://bloximages.newyork1.vip.townnews.com/tylerpaper.com/content/tncms/assets/v3/editorial/3/15/315fbeb6-b778-5c36-a542-0e7bfbafe9f0/63b49b67f391c.image.jpg?crop=1717%2C901%2C0%2C152&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@https://twitter.com/Tylerpaper",
      _score: null,
      _id: "89ecf734bab437d5f194e6984d1f865d",
    },
    {
      title: "EWD-CHISHOLM CHALLENGE",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.aqha.com/-/ewd-chisholm-challenge-fort-worth-stock-show-1",
      clean_url: "aqha.com",
      excerpt:
        "Event Classes: Class Level Divisions AGED GELDINGS AM|OP|YT AGED MARES AM|OP|YT AGED STALLIONS AM|OP ALL AROUND AM|OP|YT ALL AROUND 3RD PLACE AM|OP|YT ALL AROUND RUNNER UP AM|OP|YT BARREL RACING",
      summary:
        "Event Classes: Class Level Divisions AGED GELDINGS AM|OP|YT AGED MARES AM|OP|YT AGED STALLIONS AM|OP ALL AROUND AM|OP|YT ALL AROUND 3RD PLACE AM|OP|YT ALL AROUND RUNNER UP AM|OP|YT BARREL RACING AM|YT CUTTING AM|YT DALLY TEAM ROPING-HEADING AM DALLY TEAM ROPING-HEELING AM GRAND CHAMPION GELDINGS AM|OP|YT GRAND CHAMPION MARES AM|OP|YT GRAND CHAMPION STALLIONS AM|OP HUNT SEAT EQUITATION AM HUNT SEAT EQUITATION - Level 1 L1 AM|YT HUNT SEAT EQUITATION 13 AND UNDER YT HUNT SEAT EQUITATION 14-18 YT HU",
      rights: "aqha.com",
      rank: 43435,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media: "https://www.aqha.com/o/aqha-theme/images/favicon-aqha.ico",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "507ac5fe5167138261760cc3dee5b347",
    },
    {
      title: "Activists Slam Trump for Blaming Pro Life for Midterms",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.wbap.com/news/activists-slam-trump-for-blaming-pro-life-for-midterms",
      clean_url: "wbap.com",
      excerpt: "Activists Slam Trump for Pinning GOP Losses on Pro-Lifers",
      summary:
        "Activists are slamming former President Donald Trump for pinning the GOP midterm losses on the pro-life movement.\n\nThe former president took to his social media platform Truth Social on Sunday to argue the disappointing performance of Republicans in the midterms was not his 'fault.'\n\n'It was the \u2018abortion issue,' poorly handled by many Republicans, especially those that firmly insisted on no exceptions, even in the case of rape, incest, or life of the mother, that lost large numbers of voters,' Trump wrote.",
      rights: "wbap.com",
      rank: 86294,
      topic: "news",
      country: "FR",
      language: "en",
      authors: "",
      media:
        "https://express-images.franklymedia.com/6616/sites/274/2018/06/18145630/WBAP_FB_1200x630.png",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "470f49a5bf29e023a051c5b5285538fe",
    },
    {
      title: "Connor M. Whitaker, MD,is recognized by Continental Who's Who",
      author: "Continental Who'S Who",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "full",
      link: "https://www.prnewswire.com/news-releases/connor-m-whitaker-mdis-recognized-by-continental-whos-who-301712788.html",
      clean_url: "prnewswire.com",
      excerpt:
        "/PRNewswire/ -- Connor M. Whitaker, MD, is being recognized by Continental Who's Who as a Distinguished Healthcare Provider for his work as a Family Medicine...",
      summary:
        "PLATTSBURGH, N.Y., Jan. 3, 2023 /PRNewswire/ -- Connor M. Whitaker, MD, is being recognized by Continental Who's Who as a Distinguished Healthcare Provider for his work as a Family Medicine Resident at Champlain Valley Physicians Hospital.\u00a0 \u00a0\u00a0\nDr. Whitaker earned a Bachelor of Science and a Master of Science in biomedical science from Colorado State University in Fort Collins. He continued his education with a Doctor of Medicine from Oakland University William Beaumont School of Medicine in Oakland County, MI.",
      rights: "prnewswire.com",
      rank: 190,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Continental Who'S Who",
      media:
        "https://www.prnewswire.com:443/content/dam/prnewswire/icons/2019-Q4-PRN-Icon-32-32.png",
      is_opinion: false,
      twitter_account: "@PRNewswire",
      _score: null,
      _id: "a1e8c4c8a438a800a8ce954d686b2b82",
    },
    {
      title:
        "Fisherman attacked in Animas River by hammer-wielding man in Durango",
      author: "Garret Jaros",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.durangoherald.com/articles/fisherman-attacked-in-animas-river-by-hammer-wielding-man-in-durango/",
      clean_url: "durangoherald.com",
      excerpt:
        "A man fishing in the Animas River on Thursday was attacked from behind by a hammer-wielding man who later told police he had gone to the river with the intent of hurting or killing someone, according\u2026",
      summary:
        "Alleged attacker told police he wanted to hurt or kill someone A man fishing in the Animas River on Thursday was attacked from behind by a hammer-wielding man who later told police he had gone to the river with the intent of hurting or killing someone, according to law enforcement. Suspect Harrison Charles Hill, 23, is being held on suspicion of first-degree assault, a class 4 felony, for attacking Kenneth Riddle, 63, of Durango, while Riddle was in the river fishing behind 555 Rivergate Lane, where Hill lives with his parents, according to the Durango Police Department.",
      rights: "durangoherald.com",
      rank: 13843,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Garret Jaros",
      media:
        "https://imengine.public.prod.dur.navigacloud.com/?uuid=2ab6f77a-0371-585b-8851-e5cd1e326f77&function=fit&type=preview",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "f35b59bd9c5bf039470efc6697d5ee31",
    },
    {
      title: "FIDIC Golden Principles Under Dutch Law in 2023",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.natlawreview.com/article/fidic-golden-principles-under-dutch-law-2023",
      clean_url: "natlawreview.com",
      excerpt:
        "FIDIC contracts are widely used in the international Real Estate Projects industry. Much like their national Dutch counterpart, the UAV/UAV-GC contracts, FIDIC contracts consist of General Conditions",
      summary:
        "FIDIC contracts are widely used in the international Real Estate Projects industry. Much like their national Dutch counterpart, the UAV/UAV-GC contracts, FIDIC contracts consist of General Conditions and Special Conditions regarding project-specific issues. Examples include the industry-recognized FIDIC Red, Silver, Yellow, and Pink Books for various types of construction contracts.\nTemplate contract documents likes FIDIC and UAV/UAV-GC contracts aim to provide a set of pre-determined balanced contract conditions.",
      rights: "natlawreview.com",
      rank: 3079,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://www.natlawreview.com/sites/default/files/styles/social_media/public/article/aux/22623/real%20estate%20construction%20architectural%20plans%20calculator_1_0.jpg?itok=8nYQo3j4",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "0685654e7f8babcaf70dc7fb8ea1285c",
    },
    {
      title: "Local state reps get their committee assignments",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kentuckynewera.com/news/article_af44ab39-6252-5cea-a5e4-0988168346cd.html",
      clean_url: "kentuckynewera.com",
      excerpt:
        "The Kentucky House of Representatives announced the state representatives who will serve on key House Committees in the 2023 Kentucky General Assembly.",
      summary:
        "Additionally, Petrie will serve as ex-officio on the following budget review subcommittees (BR Sub): BR Sub on Primary and Secondary Education and Workforce Development, BR Sub on General Government, BR Sub on Health and Family Services, BR Sub on Economic Development, Public Protection, Tourism, and Environment, BR Sub on Justice, Public Safety, and Judiciary, BR Sub on Personnel, Public Pensions, and Finance, BR Sub on Post-Secondary Education, and BR Sub on Transportation.",
      rights: "kentuckynewera.com",
      rank: 90620,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://bloximages.chicago2.vip.townnews.com/kentuckynewera.com/content/tncms/custom/image/98afc73a-d605-11e7-83b4-4fc87c2d41c0.png?crop=282%2C282%2C109%2C0&resize=200%2C200&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@kentuckynewera",
      _score: null,
      _id: "8ef3099e33278fe6f9703da07bc35b28",
    },
    {
      title:
        "'A very real danger': Californians urged to avoid flooded roads after drowning death",
      author: "Andrew Chamings",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "http://www.msn.com/en-us/weather/topstories/a-very-real-danger-californians-urged-to-avoid-flooded-roads-after-drowning-death/ar-AA15VXif",
      clean_url: "msn.com",
      excerpt:
        "A historic week of rainstorms and flooding in California shows no sign of letting up. The Sacramento region \u2014 which saw evacuation orders, broken levees, shelter-in-place orders and a drowning death\u2026",
      summary:
        "A historic week of rainstorms and flooding in California shows no sign of letting up. The Sacramento region \u2014 which saw evacuation orders, broken levees, shelter-in-place orders and a drowning death over the weekend \u2014 is bracing for another deluge Wednesday and Thursday.\nVehicles stuck in a lake of water covering Highway 99 after an atmospheric river soaked Northern California, Dec. 31, 2022.\nAfter a lull Tuesday, up to 4 inches of rain is expected in Sacramento County over the next two days, with up to 7 inches in the mountains.",
      rights: "msn.com",
      rank: 100,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Andrew Chamings",
      media:
        "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA15TGQ5.img?h=630&w=1200&m=6&q=60&o=t&l=f&f=jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "cb7a581f1bc088fe76a26add51bb39fa",
    },
    {
      title:
        "Your Illinois News Radar \u00bb Inaugural ball ticket sales, contributions will benefit the Jesse White Foundation and the Central Illinois Foodbank",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://capitolfax.com/2023/01/03/inaugural-ball-ticket-sales-contributions-will-benefit-the-jesse-white-foundation-and-the-central-illinois-foodbank",
      clean_url: "capitolfax.com",
      excerpt:
        "* Press release\u2026 Today, the Pritzker-Stratton Inaugural Committee announced the charitable partner organizations that will receive the proceeds from ticket sales and contributions made to the\u2026",
      summary:
        "* Press release\u2026\nToday, the Pritzker-Stratton Inaugural Committee announced the charitable partner organizations that will receive the proceeds from ticket sales and contributions made to the inaugural committee: the Jesse White Foundation and the Central Illinois Foodbank. \nThe inaugural committee is proud to partner with the foundation of one of our greatest statesmen\u2014Jesse White, who has built a legacy of service and leadership in Illinois. Donations will support his foundation's extensive programming, which benefits at-risk youth and provides educational opportunities for low-income students in the state.",
      rights: "capitolfax.com",
      rank: 101134,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media: "https://capitolfax.com/icon.jpg",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "f73aea6f1b75394dacdf5b5b14b592b6",
    },
    {
      title:
        "U.S. accidentally proves it could not have spotted the virus in China in November 2019",
      author: "ayite",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://article.wn.com/view/2023/01/03/US_accidentally_proves_it_could_not_have_spotted_the_virus_i_j/",
      clean_url: "wn.com",
      excerpt:
        "Photo: Creative Commons In a recent article I asked why U.S. intelligence officials were following the coronavirus outbreak in China in November 2019 when there is no evidence anyone in China was\u2026",
      summary:
        "Photo: Creative Commons In a recent article I asked why U.S. intelligence officials were following the coronavirus outbreak in China in November 2019 when there is no evidence anyone in China was aware of or concerned about the virus at that point. I noted that no evidence had been produced to explain how they spotted it and why they were... read\u00a0full\u00a0story Photo: COVID S. Cov-2 pills on blue background.",
      rights: "wn.com",
      rank: 2552,
      topic: "news",
      country: "US",
      language: "en",
      authors: "ayite",
      media:
        "https://ecdn2.wn.com/o25/ph/img/d4/c2/526010a4fc1debc0362133124d96-grande.jpg",
      is_opinion: false,
      twitter_account: "@worldnewsdotcom",
      _score: null,
      _id: "b0697d55fe3a0e06d6b40ce9171df3df",
    },
    {
      title: "Vehicle versus pedestrian crash shuts down Eugene street",
      author: "Robert Desaulniers",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kezi.com/news/vehicle-versus-pedestrian-crash-shuts-down-eugene-street/article_00dd8afc-8bca-11ed-8c55-c3efb57a87d7.html",
      clean_url: "kezi.com",
      excerpt:
        "Eugene police are requesting that residents avoid Sixth Avenue between Lincoln Street and Lawrence Street.",
      summary:
        "SchoolWatch Local School Information \n KEZI 9 News: Download Our Apps \n EUGENE, Ore. -- A vehicle versus pedestrian crash has closed part of Sixth Avenue in Eugene, Eugene Police Department said.Eugene police are requesting that residents avoid Sixth Avenue between Lincoln Street and Lawrence Street. EPD says emergency responders are currently in the area responding to an incident where a vehicle struck a pedestrian. EPD has not announced a time when the road will be open.Records show the collision was reported at about 4:17 p.",
      rights: "kezi.com",
      rank: 34762,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Robert Desaulniers",
      media:
        "https://bloximages.newyork1.vip.townnews.com/kezi.com/content/tncms/assets/v3/editorial/3/6c/36c44912-965c-11ec-919d-6f881f1cb93c/62190afba0ecb.image.jpg?crop=640%2C336%2C0%2C11&resize=640%2C336&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@KEZI9",
      _score: null,
      _id: "4b15bf5d32549476be4089dbcf0059ce",
    },
    {
      title:
        "Waterford News & Star \u2014 Marcus Rashford strikes again as Manchester United outclass Bournemouth",
      author: "ter",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://waterford-news.ie/2023/01/03/marcus-rashford-strikes-again-as-manchester-united-outclass-bournemouth/",
      clean_url: "waterford-news.ie",
      excerpt:
        "Tuesday, January 03, 2023 By Ian Parker, PA Marcus Rashford scored for a fourth consecutive game as Manchester United eased to a 3-0 win over Bournemouth. Goals from Casemiro and Luke Shaw had already\u2026",
      summary:
        "Tuesday, January 03, 2023 \n\nBy Ian Parker, PA\nMarcus Rashford scored for a fourth consecutive game as Manchester United eased to a 3-0 win over Bournemouth.\nGoals from Casemiro and Luke Shaw had already put United in command and this result had a routine feel \u2013 something that has been missing at Old Trafford in recent times but which is returning as Erik ten Hag shifts the mentality of this club.\nUnited were not at their free-flowing best \u2013 Casemiro's goal was the only shot on target in the first half \u2013 but did not need to be against a Bournemouth side who never looked like threatening what would have been a first ever league victory in Manchester.",
      rights: "waterford-news.ie",
      rank: 281156,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "ter",
      media:
        "https://img.resized.co/breaking-news/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5icmVha2luZ25ld3MuaWVcXFwvcHJvZFxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDFcXFwvMDMyMjEyNTdcXFwvMi43MDQzOTA0My1lMTY3Mjc4NDA1ODgzMS5qcGdcIixcIndpZHRoXCI6NjAwLFwiaGVpZ2h0XCI6bnVsbCxcImRlZmF1bHRcIjpcImh0dHBzOlxcXC9cXFwvd3d3LmJyZWFraW5nbmV3cy5pZVxcXC9pbWFnZXNcXFwvbm8taW1hZ2UucG5nXCIsXCJvcHRpb25zXCI6W119IiwiaGFzaCI6Ijg1MjA4NTQ1ZjNkMzMxMjIxZWVkYWE0MjFmYzRmZTk1YWJiOTg5NzEifQ==/2-70439043-e1672784058831.jpg",
      is_opinion: false,
      twitter_account: "@waterfordNS",
      _score: null,
      _id: "bfb9885292d40dbb75dc60539baa9ca1",
    },
    {
      title: "Los Angeles police shoot and kill man armed with large knife",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://apnews.com/4e1a6f7962b18d925c3f87914872a931",
      clean_url: "apnews.com",
      excerpt:
        "Authorities say a man armed with a knife was shot and killed by Los Angeles police. Police say the shooting happened Monday after officers responded for a domestic violence restraining",
      summary:
        "Copyright 2023 The Associated Press. All rights reserved. This material may not be published, broadcast, rewritten or redistributed without permission. To continue, please log in, or sign up for a new account. We offer one free story view per month. If you register for an account, you will get two additional story views. After those three total views, we ask that you support us with a subscription. A subscription to our digital content is so much more than just access to our valuable content. It means you're helping to support a local community institution that has, from its very start, supported the betterment of our society.",
      rights: "smdailyjournal.com",
      rank: 353,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://bloximages.newyork1.vip.townnews.com/smdailyjournal.com/content/tncms/custom/image/0b0b7a5a-a1d1-11e6-9041-cbc40d61c8f5.jpg?resize=600%2C315",
      is_opinion: false,
      twitter_account: "@smdailyjournal",
      _score: null,
      _id: "c0e745251b59ef1ef37ee15c9c025e3f",
    },
    {
      title: "4 choices that matter in a startup strategy",
      author: "Meredith Somers",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "http://mitsloan.mit.edu/ideas-made-to-matter/4-choices-matter-a-startup-strategy",
      clean_url: "mit.edu",
      excerpt:
        "Choosing the right customer, technology, competition, and organization are necessary decisions for a successful startup.",
      summary:
        "Two years after Socrates Rosenfeld, MBA '14, graduated from MIT Sloan, he returned to campus with co-founders and an idea: Get into the cannabis industry. Rosenfeld had used cannabis to treat lingering stress and anxiety from his time as a U.S. army ranger and had watched the legalization of recreational marijuana across the country. He approachedand\u00a0both with MIT Sloan's Technological Innovation, Entrepreneurship, and Strategic Management group, for advice on how he could start a business at the intersection of cannabis legalization and the internet.",
      rights: "mit.edu",
      rank: 101,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Meredith Somers",
      media:
        "http://mitsloan.mit.edu/sites/default/files/styles/og_image/public/2023-01/leaves-2_1.jpg?h=e5a814fa&itok=4FDFaixX",
      is_opinion: false,
      twitter_account: "MITSloan",
      _score: null,
      _id: "91137fa84c14a8a8a9c4e1e451b00443",
    },
    {
      title:
        "The World of Steel and Metal Industry gathers next September in Egypt",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.foundry-planet.com/d/the-world-of-steel-and-metal-industry-gathers-next-september-in-egypt/",
      clean_url: "foundry-planet.com",
      excerpt:
        "The World of Steel and Metal Industry gathers next September in Egypt",
      summary:
        "Metal & Steel Middle East 2023 will continue the success and makes the history in the Middle East & Africa with hosting the world's leading trade fairs in Germany and beyond - Tube / Wire \u2013 METEC / GIFA Middle East Africa- 'Bright World of Metals' . Pressemitteilung | Reading time: min Their launch concurrently with Metal & Steel ME 2023 is a milestone in the industry and it will leverage their respective advantages to promote technological innovation, green and intelligent transformation, focus on industry trending topics and provide a brand-new upgraded trade platform to present the state-of-the-art products, technologies and solutions from a professional perspective.",
      rights: "foundry-planet.com",
      rank: 485310,
      topic: "news",
      country: "unknown",
      language: "en",
      authors: "",
      media:
        "https://www.foundry-planet.com/fileadmin/user_upload/19-12-22-FABEX_Daily_Slider.PNG",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "c06958f21fe7ed44b0ef185e1671c9c2",
    },
    {
      title:
        "Brooklyn subway mass shooter pleads guilty, House adjourns after McCarthy speaker standoff, and more top news",
      author: "Michael R. Sisak",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://siouxcityjournal.com/news/national/brooklyn-subway-mass-shooter-pleads-guilty-house-adjourns-after-mccarthy-speaker-standoff-and-more-top/article_85adca20-c326-5855-bc26-c11ff192d6d7.html",
      clean_url: "siouxcityjournal.com",
      excerpt:
        "A man who opened fire on a packed Brooklyn subway train last year, wounding 10, pleaded guilty Tuesday to federal terrorism charges. Get that and more of today's top news here.",
      summary:
        "A man who opened fire on a packed Brooklyn subway train last year, wounding 10 passengers in a rush-hour attack that shocked New York City, pleaded guilty Tuesday to federal terrorism charges that could put him in prison for the rest of his life.Frank James, 63, who posted online that he was the 'Prophet of Doom,' admitted in Brooklyn federal court to pulling the trigger on a Manhattan-bound train as it moved between stations on April 12, 2022 \u2014 an assault that prosecutors said was 'intended to inflict maximum damage at the height of rush hour.",
      rights: "siouxcityjournal.com",
      rank: 9791,
      topic: "news",
      country: "US",
      language: "en",
      authors:
        "Alex Brandon,Associated Press,CNN,Chloe Melas,Farnoush Amiri,John Wawrow,Kevin Freking,Lisa Mascaro,Michael R. Sisak,Nouran Salahieh",
      media:
        "https://bloximages.chicago2.vip.townnews.com/siouxcityjournal.com/content/tncms/assets/v3/editorial/8/5a/85adca20-c326-5855-bc26-c11ff192d6d7/63b4cafe642bd.preview.jpg?crop=1763%2C926%2C0%2C124&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@scj",
      _score: null,
      _id: "f31fcd24099a1f57471c0bf1cbe45d35",
    },
    {
      title: "Medical expert weighs in on Bills player's cardiac arrest",
      author: "Nadia Galindo",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://westchester.news12.com/medical-expert-weighs-in-on-bills-players-cardiac-arrest",
      clean_url: "news12.com",
      excerpt:
        "While the cause of the medical episode is unclear, it happened moments after Buffalo Bills safety Damar Hamlin tackled a Bengals wide receiver.",
      summary:
        'The Bills confirmed the 24-year-old suffered cardiac arrest."It\'s not a heart attack," said Dr. Julio Panza, director of cardiology at Westchester Medical Center. "Cardiac arrest is situation where for one of many reasons that the heart, which is a pump is not pumping right. Therefore there is no blood circulation head to toe."For that reason, Panza said it is crucial to get the heartbeat restored immediately."Any second without blood going to the brain is a risk for brain injury," he said.Within 10 seconds of Hamlin collapsing, team trainers were on the field and began delivering lifesaving CPR before he was taken to the hospital where he is sedated and remains in critical condition.',
      rights: "news12.com",
      rank: 5228,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Nadia Galindo",
      media:
        "https://images.ctfassets.net/3kqcuzntcg31/6bCSE3DWO8fQqvSUGDYZTM/a8bb41d1b1fa01e18b980bd3e4e54950/31cf3798-2baa-403d-a686-a4647ac63eef.jpg",
      is_opinion: false,
      twitter_account: "@News12WC",
      _score: null,
      _id: "78ad928308f51ef4b64f79fcc4fea822",
    },
    {
      title: "Missoula food bank nears holiday goal, still taking donations",
      author: "Zoe Buchli",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://missoulian.com/news/local/missoula-food-bank-nears-holiday-goal-still-taking-donations/article_e8b83d9f-090a-5a3a-a4d5-2bf24fefc0fe.html",
      clean_url: "missoulian.com",
      excerpt:
        "The Missoula Food Bank and Community Center received $316,000 in cash donations for its annual holiday drive this year, making it the most a single fundraiser has brought in to",
      summary:
        "The Missoula Food Bank and Community Center attracted over $316,000 in cash donations for its annual holiday drive this year, making it the most a single fundraiser has brought in to date.The food bank's goal was $325,000 for its 37th Holiday Drive fundraiser, and Executive Director Amy Allison Thompson expects more donations to trickle in through the coming week.'I am extremely excited about it,' Allison Thompson said. 'This particular goal is a very lofty goal.'The $316,132.75 came from Missoulians and people invested in the Missoula food bank's work, Allison Thompson said.",
      rights: "missoulian.com",
      rank: 7738,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Tom Bauer,Zoe Buchli",
      media:
        "https://bloximages.chicago2.vip.townnews.com/missoulian.com/content/tncms/assets/v3/editorial/d/42/d424b173-c989-579f-9130-1abdd55f2d7f/63b4bc5d11171.image.jpg?crop=1763%2C926%2C0%2C124&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@missoulian",
      _score: null,
      _id: "9568d179e7db89832c1271dba6fc1f69",
    },
    {
      title:
        "Rob Wagner prepares to take reins as first new Oregon Senate president in decades",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.heraldandnews.com/news/rob-wagner-prepares-to-take-reins-as-first-new-oregon-senate-president-in-decades/article_3e5ab1a0-8bcc-11ed-af5d-4346189b4890.html",
      clean_url: "heraldandnews.com",
      excerpt:
        "Rob Wagner first walked into the Oregon Capitol in 1997 as an intern for a first-term Democratic state senator from Portland. In January, as his first political boss, Gov. Kate",
      summary:
        "Sen. Rob Wagner, D-Lake Oswego, listens from his desk Dec. 9, 2022, to other senators speak on the Senate floor. Connor Radnovich/Oregon Capital Chronicle",
      rights: "heraldandnews.com",
      rank: 41245,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://bloximages.chicago2.vip.townnews.com/heraldandnews.com/content/tncms/assets/v3/editorial/7/f6/7f67ede8-8bcc-11ed-b545-c3b5dce431f9/63b4d2142e13e.image.jpg?crop=1890%2C992%2C0%2C51&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@HeraldandNews",
      _score: null,
      _id: "812ce9a2e0e856dc34dccf3db64a07b3",
    },
    {
      title: "On Harbaugh Watch 2023",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://mgoblog.com/content/harbaugh-watch-2023",
      clean_url: "mgoblog.com",
      excerpt: "I'm going to need a second source.",
      summary:
        'The short version is I don\'t know anything. But I can\'t focus on UFR, and threw out a Neck Sharpies, and already updated my starts and snaps data for the year, so we might as well talk about it.\nWhat\'s the evidence that Harbaugh is pursuing NFL jobs?\nCredible reporters say so. Bruce Feldman reported "multiple sources close to Jim Harbaugh" believe he would take an NFL coaching job if it was offered. One source used the "done deal" phrasing. Feldman is a guy we are pretty sure Harbaugh or at least his staff have a strong rapport with.',
      rights: "mgoblog.com",
      rank: 66259,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media:
        "https://mgoblog.com/sites/default/files/2023-01/Screenshot%202023-01-03%20163824.jpg",
      is_opinion: false,
      twitter_account: "@mgoblog",
      _score: null,
      _id: "20a899250d32d9c739454a3d28f1984a",
    },
    {
      title:
        "National group complains to U.S. Department of Education about Ashland School District",
      author: "Jerry Howard",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kdrv.com/news/national-group-complains-to-u-s-department-of-education-about-ashland-school-district/article_1363ce80-8bb0-11ed-b778-67152a7918c1.html",
      clean_url: "kdrv.com",
      excerpt:
        "ASHLAND, Ore. -- A national group says it filed a complaint today with the U.S. Department of Education against the Ashland School District.",
      summary:
        'ASHLAND, Ore. -- A national group says it filed a complaint today with the U.S. Department of Education against the Ashland School District.Parents Defending Education (PDE) shared its 18-page complaint which includes three pages of narrative and 15 pages of exhibits to support its claim of\u00a0racial and ethnic bias for the Ashland School District\'s (ASD) "affinity groups," which are groups intended for student inclusion, such as Native American students, Hispanic, LGBTQ, etc.PDE describes itself as "a national grassroots organization working to reclaim our schools from activists imposing harmful agendas.',
      rights: "kdrv.com",
      rank: 30941,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Jerry Howard",
      media:
        "https://bloximages.newyork1.vip.townnews.com/kdrv.com/content/tncms/assets/v3/editorial/a/b4/ab43ac1e-f313-52fe-a7b8-6b29b4693d5d/61def757200bb.image.jpg?crop=700%2C368%2C0%2C41&resize=700%2C368&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@kdrv",
      _score: null,
      _id: "94e139df0db0ac2d916ce84faf37121d",
    },
    {
      title: "dailyunion.com",
      author: "Daily Jefferson County Union",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.dailyunion.com/news/state/study-toxic-pfas-chemical-plume-detected-in-green-bay/article_f83ac0f9-92f3-5551-a1ab-ea1b2ea08e99.html",
      clean_url: "dailyunion.com",
      excerpt: "This page no longer exists or has been removed",
      summary:
        "The page may have moved, you may have mistyped the address, or followed a bad link.\n\nVisit our homepage, or search for whatever you were looking for\u2026",
      rights: "dailyunion.com",
      rank: 84495,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Daily Jefferson County Union",
      media:
        "https://bloximages.newyork1.vip.townnews.com/dailyunion.com/content/tncms/custom/image/cf15f7e8-eee5-11eb-a3eb-2b5754d09ad7.jpg",
      is_opinion: false,
      twitter_account: "@DUNews",
      _score: null,
      _id: "bd57c2fd9a2dd2e07004260bc9b32fe7",
    },
    {
      title:
        "Waterford News & Star \u2014 Arsenal's momentum halted after frustrating draw with Newcastle",
      author: "ter",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://waterford-news.ie/2023/01/03/arsenals-momentum-halted-after-frustrating-draw-with-newcastle/",
      clean_url: "waterford-news.ie",
      excerpt:
        "Tuesday, January 03, 2023 By Ed Elliot, PA Arsenal missed the chance to move 10 points clear at the top of the Premier League after their 100 per cent home record was ended by a frustrating goalless\u2026",
      summary:
        "Tuesday, January 03, 2023 \n\nBy Ed Elliot, PA\nArsenal missed the chance to move 10 points clear at the top of the Premier League after their 100 per cent home record was ended by a frustrating goalless draw with high-flying Newcastle.\nThe Gunners faded from a promising start and rarely threatened to break down the division's stingiest defence during a forgettable evening at a sold-out Emirates Stadium.\nBoth sides had penalty appeals waved away but neither could genuinely claim to deserve more than a point from a fractious encounter of eight yellow cards but few chances.",
      rights: "waterford-news.ie",
      rank: 281156,
      topic: "news",
      country: "IE",
      language: "en",
      authors: "ter",
      media:
        "https://img.resized.co/breaking-news/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5icmVha2luZ25ld3MuaWVcXFwvcHJvZFxcXC91cGxvYWRzXFxcLzIwMjNcXFwvMDFcXFwvMDMyMTUzNTlcXFwvMi43MDQzODk3Ny1lMTY3Mjc4MjkyMDY4Ny5qcGdcIixcIndpZHRoXCI6NjAwLFwiaGVpZ2h0XCI6bnVsbCxcImRlZmF1bHRcIjpcImh0dHBzOlxcXC9cXFwvd3d3LmJyZWFraW5nbmV3cy5pZVxcXC9pbWFnZXNcXFwvbm8taW1hZ2UucG5nXCIsXCJvcHRpb25zXCI6W119IiwiaGFzaCI6ImIzMzE0ZDZmYjZkZWU4NDc3YjcxYjMyMjNlYjIzZTFkMWY1YTMwM2EifQ==/2-70438977-e1672782920687.jpg",
      is_opinion: false,
      twitter_account: "@waterfordNS",
      _score: null,
      _id: "caabf42dd8ee08cb704e4ebd9192f940",
    },
    {
      title:
        "House adjourns without a speaker as McCarthy fails to lock down votes",
      author: "Clare Foran",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.waaytv.com/news/house-adjourns-without-a-speaker-as-mccarthy-fails-to-lock-down-votes/article_457ab188-26da-5bb1-b531-66696ab7396b.html",
      clean_url: "waaytv.com",
      excerpt:
        "The House of Representatives moved to adjourn until Wednesday after Republican Kevin McCarthy failed to secure the support needed to win in three rounds of voting on Tuesday.",
      summary:
        "The House of Representatives moved to adjourn until Wednesday after Republican Kevin McCarthy failed to secure the support needed to win in three rounds of voting on Tuesday.The new House GOP majority is locked in a once-in-a-century fight while McCarthy has defiantly vowed to stay in the race as he continues his increasingly imperiled bid for speaker. The last time an election for speaker went to multiple ballots was in 1923.LIVE UPDATES: The latest on the new Congress and House speaker voteThe new House Republican majority is now engaged in a contentious, drawn-out fight that threatens to deepen divides within the party with McCarthy's political career on the line.",
      rights: "waaytv.com",
      rank: 18998,
      topic: "news",
      country: "US",
      language: "en",
      authors:
        "Alex Brandon Ap,Annie Grayer,Clare Foran,Kristin Wilson,Melanie Zanona",
      media:
        "https://bloximages.newyork1.vip.townnews.com/waaytv.com/content/tncms/assets/v3/editorial/e/59/e59f4db4-8317-5cf7-895e-b9ee2b4732f9/63b4a7b5d7aca.image.jpg?crop=1920%2C1008%2C0%2C35&resize=1200%2C630&order=crop%2Cresize",
      is_opinion: false,
      twitter_account: "@WAAYTV",
      _score: null,
      _id: "a637b6185d2216fcea48dc44ecd6cb48",
    },
    {
      title:
        "Federal officers seeing an uptick of cocaine, other hard drugs seized at ports of entry",
      author: "Vanessa Croix",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.kens5.com/article/news/special-reports/at-the-border/federal-officers-drugs-border/273-e321cf08-6e58-4421-8b70-b640b86e7db0",
      clean_url: "kens5.com",
      excerpt:
        "The amount of cocaine seized in Fiscal Year 2022 is up 19 percent from last year, totally over 10,000 pounds.",
      summary:
        "LAREDO, Texas \u2014 Drugs, guns, and ammo, those are just some of the items criminals try to smuggle into the United States every day, according to U.S. Customs and Border Protection. At eight South Texas ports of entry, CBP officials said they're seeing a spike in smugglers trying to get hard drugs, like cocaine and methamphetamine into the U.S. Between October of 2021 and September of this year, CBP officers seized 47,755 pounds of drugs with an estimated street value of $436 million. \u00a0\u00a0 Officials said the amount of cocaine seized is up 19 percent from last year, as they're also seeing a spike in other drugs at the ports of entry including including marijuana, methamphetamine, heroin, and fentanyl.",
      rights: "kens5.com",
      rank: 10321,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Vanessa Croix",
      media:
        "https://media.kens5.com/assets/KENS/images/b8d69032-f3d0-47de-9074-1e0a7da84867/b8d69032-f3d0-47de-9074-1e0a7da84867_1140x641.jpg",
      is_opinion: false,
      twitter_account: "KENS5",
      _score: null,
      _id: "7292e3dcb06cfc67bb332e67f355cd00",
    },
    {
      title:
        "Jeremy Renner shares hospital selfie following snow plow accident, expresses gratitude for",
      author: "ANI 4th",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.bignewsnetwork.com/news/273310563/jeremy-renner-shares-hospital-selfie-following-snow-plow-accident-expresses-gratitude-for-kind-words",
      clean_url: "bignewsnetwork.com",
      excerpt:
        "Hollywood star Jeremy Renner who suffered from a traumatic injury after an accident on New Year Day has shared a selfie from his hospital bed thanking ever",
      summary:
        'ANI 4th January 2023, 12:18 GMT+11Washington [US], January 4 (ANI): Hollywood star Jeremy Renner, who suffered from a traumatic injury after an accident on New Year\'s Day, has shared a selfie from his hospital bed, thanking everyone for their "kind words."Taking to Instagram, Renner shared the picture along with the caption, "Thank you all for your kind words. Im too messed up now to type. But I send love to you all."The comments section of the social media post was filled with wishes from several Hollywood stars including Chris Hemsworth, Chris Pratt, Taika Watiti and Orlando Bloom among others.',
      rights: "bignewsnetwork.com",
      rank: 5608,
      topic: "news",
      country: "US",
      language: "en",
      authors: "ANI 4th",
      media:
        "https://static.bignewsnetwork.com/bnn/images/big-news-network-slogan.jpg",
      is_opinion: false,
      twitter_account: "@BigNewsNetwork",
      _score: null,
      _id: "a24786e21d55f8c6237eb560933da4cb",
    },
    {
      title: "Ben Herbert associatie hired as S&C coach at Purdue",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://mgoblog.com/mgoboard/ben-herbert-associatie-hired-sc-coach-purdue",
      clean_url: "mgoblog.com",
      excerpt:
        "Really great opportunity for him. Wish him the best, except against Michigan. \u00a0 #Purdue is expected to hire Kiero Small as director of strength and conditioning. Small was Michigan football Associate Director of Strength and Conditioning. He played fullback at Arkansas and was a 7th round pick of the Seahawks in 2014.",
      summary:
        "jdib \n\nJanuary 3rd, 2023 at 7:45 PM\n^\n\nYeah my heart sank when I thought Herbert was gone the way you worded this title.\u00a0 Dude has made a massive impact on our players year-to-year.\u00a0\nWould be detrimental to lose him.\u00a0 Don't do that to us, op!",
      rights: "mgoblog.com",
      rank: 66259,
      topic: "news",
      country: "US",
      language: "en",
      authors: "",
      media: "https://mgoblog.com/favicon.ico",
      is_opinion: false,
      twitter_account: "@mgoblog",
      _score: null,
      _id: "22cc41a2109eabf91f5000b6cbf73234",
    },
    {
      title: "Ronna McDaniel to Newsmax: Disinfo Campaign Skewing My Polls",
      author: "",
      published_date: "2023-01-04 01:45:00",
      published_date_precision: "timezone unknown",
      link: "https://www.wbap.com/news/ronna-mcdaniel-to-newsmax-disinfo-campaign-skewing-my-polls",
      clean_url: "wbap.com",
      excerpt: "Ronna McDaniel to Newsmax: Disinfo Campaign Skewing My Polls",
      summary:
        "Republican National Committee Chair Ronna McDaniel tells Newsmax the polls showing that a majority of GOP voters want to see a change in leadership at the RNC are skewed by her opposition's 'disinformation campaign.'\n\nAppearing Tuesday on 'Spicer & Co.', McDaniel didn't specifically name fellow RNC employee Harmeet Dhillon, her main challenger for the position in the vote set for later this month. But her responses were to Dhillon's previous Newsmax appearance in which she told 'Spicer & Co.' that the RNC needs to cut costs and 'decentralize the operations of the RNC and move some of those functions outside of D.",
      rights: "wbap.com",
      rank: 86294,
      topic: "news",
      country: "FR",
      language: "en",
      authors: "",
      media:
        "https://express-images.franklymedia.com/6616/sites/274/2018/06/18145630/WBAP_FB_1200x630.png",
      is_opinion: false,
      twitter_account: null,
      _score: null,
      _id: "762495e11ee3adb099f365759316c56c",
    },
    {
      title:
        "Wrestling: No. 14 Mount Olive racks up bonus points in win over Mendham",
      author: "Mak Ojutiku",
      published_date: "2023-01-04 01:44:50",
      published_date_precision: "full",
      link: "https://www.nj.com/highschoolsports/2023/01/wrestling-no-14-mount-olive-racks-up-bonus-points-in-win-over-mendham.html",
      clean_url: "nj.com",
      excerpt:
        "Wrestling: No. 14 Mount Olive racks up bonus points in win over Mendham",
      summary:
        "Mount Olive, No. 14 in the NJ.com Top 20, rolled to a 61-10 win over Mendham, in Mendham.\n\nThe Marauders (2-1) earned seven bonus point wins.\n\nReturning state place-winners Jack Bastarrika and Tyeler Hagensen both picked up extra points as Hagensen took a 15-0 tech over Pravith Siriwardhana at 120, while Bastarrika recorded a pin over PJ Rooney at 132.\n\nFormer fifth-place state tournament finisher Anthony Moscatello took a forfeit at 190.\n\nMatteo Eagleson gave Mount Olive five points off a tech at 126, while Tyler BIenus (175), Tyler Cumming (165), and Kristian Dobbek (144) all earned pins.",
      rights: "nj.com",
      rank: 1033,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Mak Ojutiku,Nj Advance Media,mojutiku",
      media:
        "https://www.nj.com/resizer/eyDTL-Y20V1Jy5dWEdmYGeBbp2s=/1280x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/XQU3YFA3TVH5DABJAVUDV55EKQ.jpg",
      is_opinion: false,
      twitter_account: "@njdotcom",
      _score: null,
      _id: "8534628f13315d1ce8a100f623dbbcd8",
    },
    {
      title: "PancakeSwap Trading Down 3.3% Over Last 7 Days (CAKE)",
      author: "Maddie Sorensen",
      published_date: "2023-01-04 01:44:47",
      published_date_precision: "full",
      link: "https://dakotafinancialnews.com/2023/01/04/pancakeswap-trading-down-3-3-over-last-7-days-cake.html",
      clean_url: "dakotafinancialnews.com",
      excerpt:
        "PancakeSwap (CAKE) traded 0.7% higher against the U.S. dollar during the 1-day period ending at 20:00 PM ET on January 3rd. During the last week, PancakeSwap has traded down 3.3% against the U.S.\u2026",
      summary:
        "PancakeSwap (CAKE) traded 0.7% higher against the U.S. dollar during the 1-day period ending at 20:00 PM ET on January 3rd. During the last week, PancakeSwap has traded down 3.3% against the U.S. dollar. One PancakeSwap token can now be bought for approximately $3.20 or 0.00019160 BTC on major exchanges. PancakeSwap has a market cap of $521.44 million and $15.50 million worth of PancakeSwap was traded on exchanges in the last day. \nHere's how related cryptocurrencies have performed during the last day: \nKILT Protocol (KILT) traded 2.",
      rights: "dakotafinancialnews.com",
      rank: 873414,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Maddie Sorensen",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/cryptocurrencies/pancakeswap-CAKE.png?v=2022-10-05&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@MarketBeatCom",
      _score: null,
      _id: "0ad9172b504a41bc35d09b6e99f1d862",
    },
    {
      title: "PancakeSwap Trading Down 3.3% Over Last 7 Days (CAKE)",
      author: "Emily Schoerning",
      published_date: "2023-01-04 01:44:47",
      published_date_precision: "full",
      link: "https://www.modernreaders.com/news/2023/01/04/pancakeswap-trading-down-3-3-over-last-7-days-cake.html",
      clean_url: "modernreaders.com",
      excerpt:
        "PancakeSwap (CAKE) traded 0.7% higher against the dollar during the 24 hour period ending at 20:00 PM E.T. on January 3rd. During the last week, PancakeSwap has traded 3.3% lower against the dollar.\u2026",
      summary:
        "PancakeSwap (CAKE) traded 0.7% higher against the dollar during the 24 hour period ending at 20:00 PM E.T. on January 3rd. During the last week, PancakeSwap has traded 3.3% lower against the dollar. One PancakeSwap token can currently be purchased for $3.20 or 0.00019160 BTC on popular cryptocurrency exchanges. PancakeSwap has a market capitalization of $521.44 million and $15.50 million worth of PancakeSwap was traded on exchanges in the last 24 hours. \nHere's how related cryptocurrencies have performed during the last 24 hours: \nKILT Protocol (KILT) traded 2.",
      rights: "modernreaders.com",
      rank: 448265,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Emily Schoerning",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/cryptocurrencies/pancakeswap-CAKE.png?v=2022-10-05&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@RatingsNetwork",
      _score: null,
      _id: "7cb36b2a98bc405a29d7b8a95bb63490",
    },
    {
      title: "XDC Network (XDC) Trading Down 10.4% Over Last 7 Days",
      author: "Lisa Pomrenke",
      published_date: "2023-01-04 01:44:47",
      published_date_precision: "full",
      link: "https://www.wkrb13.com/2023/01/04/xdc-network-xdc-trading-down-10-4-over-last-7-days.html",
      clean_url: "wkrb13.com",
      excerpt:
        "XDC Network (XDC) traded down 2.4% against the dollar during the 1 day period ending at 20:00 PM ET on January 3rd. One XDC Network coin can currently be bought for $0.0248 or 0.00000148 BTC on major\u2026",
      summary:
        "XDC Network (XDC) traded down 2.4% against the dollar during the 1 day period ending at 20:00 PM ET on January 3rd. One XDC Network coin can currently be bought for $0.0248 or 0.00000148 BTC on major exchanges. During the last seven days, XDC Network has traded down 10.4% against the dollar. XDC Network has a total market capitalization of $341.71 million and $2.24 million worth of XDC Network was traded on exchanges in the last 24 hours. \nHere is how other cryptocurrencies have performed during the last 24 hours: \nKILT Protocol (KILT) traded 2.",
      rights: "wkrb13.com",
      rank: 772415,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Lisa Pomrenke",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/cryptocurrencies/xdc-network-XDC.png?v=2022-10-05&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@MarketBeatCom",
      _score: null,
      _id: "c560584c5cacb6156af0e0c17ca07359",
    },
    {
      title: "Terra Classic Price Hits $0.0002 on Top Exchanges (LUNC)",
      author: "Lisa Pomrenke",
      published_date: "2023-01-04 01:44:46",
      published_date_precision: "full",
      link: "https://www.wkrb13.com/2023/01/04/terra-classic-price-hits-0-0002-on-top-exchanges-lunc.html",
      clean_url: "wkrb13.com",
      excerpt:
        "Terra Classic (LUNC) traded 0.9% lower against the US dollar during the 24-hour period ending at 20:00 PM Eastern on January 3rd. Terra Classic has a market cap of $953.76 million and approximately\u2026",
      summary:
        "Terra Classic (LUNC) traded 0.9% lower against the US dollar during the 24-hour period ending at 20:00 PM Eastern on January 3rd. Terra Classic has a market cap of $953.76 million and approximately $204.66 million worth of Terra Classic was traded on exchanges in the last 24 hours. During the last week, Terra Classic has traded down 7.7% against the US dollar. One Terra Classic coin can now be purchased for approximately $0.0002 or 0.00000001 BTC on exchanges. \nHere's how related cryptocurrencies have performed during the last 24 hours: \nTerra (LUNA) traded 0.",
      rights: "wkrb13.com",
      rank: 772415,
      topic: "news",
      country: "US",
      language: "en",
      authors: "Lisa Pomrenke",
      media:
        "https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/cryptocurrencies/terra-classic-LUNC.png?v=2022-10-05&w=240&h=240&zc=2",
      is_opinion: false,
      twitter_account: "@RatingsNetwork",
      _score: null,
      _id: "7b1d6a7cf7211c8be95883e300eb020a",
    },
  ],
  user_input: {
    lang: ["en"],
    not_lang: null,
    countries: null,
    not_countries: null,
    page: 6,
    size: 50,
    sources: null,
    not_sources: null,
    topic: "news",
    from: "2022-12-21 01:57:02",
  },
};

export default output;
