import NavBar from "./components/NavBar";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import News from "./components/News";
import LoadingBar from "react-top-loading-bar";
import { useState } from "react";

function App() {
  const apikey = process.env.REACT_APP_NEWS_API || "";
  const [progress, setProgress] = useState(0);
  const pageSize = 9;

  return (
    <>
      <Router>
        <NavBar />
        <LoadingBar
          height={3}
          color="#f11946"
          progress={progress}
          onLoaderFinished={() => progress}
        />
        <Routes>
          <Route
            path="/business"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="business"
              />
            }
          />
          <Route
            path="/entertainment"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="entertainment"
              />
            }
          />
          <Route
            path="/general"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="news"
              />
            }
          />
          <Route
            path="/"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="news"
              />
            }
          />
          <Route
            path="/beauty"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="beauty"
              />
            }
          />
          <Route
            path="/science"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="science"
              />
            }
          />
          <Route
            path="/sport"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="sport"
              />
            }
          />
          <Route
            path="/travel"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="travel"
              />
            }
          />
          <Route
            path="/food"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="food"
              />
            }
          />
          <Route
            path="/music"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="music"
              />
            }
          />
          <Route
            path="/gaming"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="gaming"
              />
            }
          />
          <Route
            path="/energy"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="energy"
              />
            }
          />
          <Route
            path="/economics"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="economics"
              />
            }
          />
          <Route
            path="/finance"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="finance"
              />
            }
          />
          <Route
            path="/politics"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="politics"
              />
            }
          />
          <Route
            path="/tech"
            element={
              <News
                setProgress={setProgress}
                apikey={apikey}
                lang="en"
                pageSize={pageSize}
                category="tech"
              />
            }
          />
        </Routes>
      </Router>
    </>
  );
}

export default App;
